repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Display the total number of messages
            "-sn", # Display the total number of non-fatal messages
            "--rcfile=.pylintrc", # Use the specified configuration file
            "--load-plugins=pylint.extensions.docparams", # Load plugins
          ]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]