version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - FLASK_ENV=development
    volumes:
      - .:/app 
    command: flask run --host=0.0.0.0 --port=5000